 const actionType = {
    TRACKER_LOGS:'TRACKER_LOGS',
    CREATE_LOGS:'CREATE_LOGS',
    SIGNUP_SUCCED:'SIGNUP_SUCCED',
    SIGNIN_SUCCED:'SIGNIN_SUCCED',
    SIGNIN_ERROR:'SIGNIN_ERROR',
    SIGNUP_ERROR:'SIGNUP_ERROR'
};
export default actionType;